DROP TABLE WE_SPACE IF EXISTS;
DROP TABLE WE_WIKI IF EXISTS;

CREATE TABLE WE_SPACE
(
	WE_SPACE_IDX integer identity,
	WE_SPACE_NAME VARCHAR(100),
	WE_SPACE_DESC VARCHAR(800),
	WE_VIEW_PRIVACY VARCHAR(20),
	WE_EDIT_PRIVACY VARCHAR(20),
	WE_ADMIN_IDX integer,
	WE_SPACE_EXPOSED VARCHAR(1),
	WE_USE_YN VARCHAR(1),
	WE_INS_USER integer,
	WE_INS_DATE DATE,
	WE_UPD_USER integer,
	WE_UPD_DATE DATE,
	PRIMARY KEY (WE_SPACE_IDX)
);

CREATE TABLE WE_WIKI
( 
	WE_WIKI_IDX integer identity,
	WE_SPACE_IDX integer,
	WE_WIKI_PARENT_IDX integer,
	WE_WIKI_ORDER_IDX integer,
	WE_WIKI_DEPTH_IDX integer,
	WE_WIKI_TITLE VARCHAR(200),
	WE_WIKI_TEXT VARCHAR,
	WE_WIKI_MARKUP VARCHAR,
	WE_WIKI_REVISION integer,
	WE_WIKI_STATUS VARCHAR(1),
	WE_WIKI_QUOTA integer,
	WE_WIKI_URL VARCHAR(50),
	WE_WIKI_AGREE integer,
	WE_WIKI_VIEW_CNT integer,
	WE_WIKI_PREV VARCHAR(50),
	WE_WIKI_NEXT VARCHAR(50),
	WE_USER_IP VARCHAR(30),
	WE_WIKI_PROTECT VARCHAR(1),
	WE_EDIT_TEXT VARCHAR(100),
	WE_USE_YN VARCHAR(1),
	WE_INS_USER integer,
	WE_INS_DATE DATE,
	WE_UPD_USER integer,
	WE_UPD_DATE DATE,
	WE_EDIT_YN VARCHAR(1),
	PRIMARY KEY (WE_WIKI_IDX)
);
