
/* Create Foreign Keys */

ALTER TABLE WE_BBS_ATTACHMENT
	ADD FOREIGN KEY (WE_BBS_IDX)
	REFERENCES WE_BBS (WE_BBS_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_BBS_COMMENT
	ADD FOREIGN KEY (WE_BBS_IDX)
	REFERENCES WE_BBS (WE_BBS_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_GROUP_USER
	ADD FOREIGN KEY (WE_GROUP_IDX)
	REFERENCES WE_GROUP_INFO (WE_GROUP_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SPACE_GROUP
	ADD FOREIGN KEY (WE_GROUP_IDX)
	REFERENCES WE_GROUP_INFO (WE_GROUP_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_ALARM_INFO
	ADD FOREIGN KEY (WE_META_IDX)
	REFERENCES WE_META_INFO (WE_META_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_USER_ALARM
	ADD FOREIGN KEY (WE_META_IDX)
	REFERENCES WE_META_INFO (WE_META_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_BBS
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SPACE_GROUP
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SPACE_IMAGE
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SPACE_JOIN
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SPACE_USER
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI
	ADD FOREIGN KEY (WE_SPACE_IDX)
	REFERENCES WE_SPACE (WE_SPACE_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_ADD_FRIEND
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_FAVORITE
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_GROUP_USER
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_PROFILE
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_SEND_MAIL
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_USER_JOB
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_USER_POSITION
	ADD FOREIGN KEY (WE_USER_IDX)
	REFERENCES WE_USER (WE_USER_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_AGREE
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_COMMENT
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_FILE
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_LINK
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_NOTE
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_SUMMARY
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_TAG
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE WE_WIKI_VIEWER
	ADD FOREIGN KEY (WE_WIKI_IDX)
	REFERENCES WE_WIKI (WE_WIKI_IDX)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;